// <auto-generated />
using System;
using Antree_Ecommerce_BE.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antree_Ecommerce_BE.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021202945_AddPriceSubscription")]
    partial class AddPriceSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeedback")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductPriceDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.ToTable("OrderDetailFeedbackMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Expire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0f6cbb8-6421-44b5-8a46-bb9038555d73"),
                            CoverImage = "",
                            CreatedBy = new Guid("b0fcf67e-0d47-4bca-8b11-1e658f4817a3"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description0",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name0",
                            Price = 0m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 0,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("05a7abb8-20dc-442e-b142-e2774a1b3849"),
                            CoverImage = "",
                            CreatedBy = new Guid("5bce0957-029c-4c28-9126-f9a529a371c0"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description1",
                            DiscountPercent = 0m,
                            DiscountSold = 1000m,
                            IsDeleted = false,
                            Name = "Name1",
                            Price = 1000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 1,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("48dba51a-1c8c-49ac-9638-74d57c4aefb6"),
                            CoverImage = "",
                            CreatedBy = new Guid("15f79e6a-49ec-49f5-bf22-e76faf3b8ed0"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description2",
                            DiscountPercent = 0m,
                            DiscountSold = 2000m,
                            IsDeleted = false,
                            Name = "Name2",
                            Price = 2000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 2,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("5a082098-80bb-4040-b4bf-d7af85c9a463"),
                            CoverImage = "",
                            CreatedBy = new Guid("37861b98-20c6-4bc0-9a2e-096843c5a9f8"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description3",
                            DiscountPercent = 0m,
                            DiscountSold = 3000m,
                            IsDeleted = false,
                            Name = "Name3",
                            Price = 3000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 3,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("71920841-5c57-4ab9-9577-946e8076de6e"),
                            CoverImage = "",
                            CreatedBy = new Guid("69602954-7d32-40ce-8016-a354dec8f148"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description4",
                            DiscountPercent = 0m,
                            DiscountSold = 4000m,
                            IsDeleted = false,
                            Name = "Name4",
                            Price = 4000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 4,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("af689836-13e0-4a2e-8a49-a14c324800ce"),
                            CoverImage = "",
                            CreatedBy = new Guid("13f9a379-fa2f-459c-917c-8e53c4190184"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description5",
                            DiscountPercent = 0m,
                            DiscountSold = 5000m,
                            IsDeleted = false,
                            Name = "Name5",
                            Price = 5000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 5,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("2b4c2e8a-6266-46ce-8d8a-28adbef856f1"),
                            CoverImage = "",
                            CreatedBy = new Guid("96c188ae-1c16-4dbb-81ed-44309a8bd1ff"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description6",
                            DiscountPercent = 0m,
                            DiscountSold = 6000m,
                            IsDeleted = false,
                            Name = "Name6",
                            Price = 6000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 6,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("9fa06791-7e61-4ee7-a55c-31650cca06da"),
                            CoverImage = "",
                            CreatedBy = new Guid("2cc8b19c-b4f4-4fcc-bbf3-4da48248b874"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description7",
                            DiscountPercent = 0m,
                            DiscountSold = 7000m,
                            IsDeleted = false,
                            Name = "Name7",
                            Price = 7000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 7,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("9ca88eb6-80db-428a-bd92-416d3bd2e3ea"),
                            CoverImage = "",
                            CreatedBy = new Guid("0e0bc4a6-16dd-4b27-a8c8-e59824d0354e"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description8",
                            DiscountPercent = 0m,
                            DiscountSold = 8000m,
                            IsDeleted = false,
                            Name = "Name8",
                            Price = 8000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 8,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("f8944915-e1bc-4386-abf3-db60285b5578"),
                            CoverImage = "",
                            CreatedBy = new Guid("153ffad0-3dbd-4010-9ed2-09da5230d5b8"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description9",
                            DiscountPercent = 0m,
                            DiscountSold = 9000m,
                            IsDeleted = false,
                            Name = "Name9",
                            Price = 9000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 9,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("0eb6901b-e426-4127-b404-ddc87457ee64"),
                            CoverImage = "",
                            CreatedBy = new Guid("a8fdb26f-4ebc-41a4-a5ae-e3540b74ed5b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description10",
                            DiscountPercent = 0m,
                            DiscountSold = 10000m,
                            IsDeleted = false,
                            Name = "Name10",
                            Price = 10000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 10,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("6660b4f2-2627-4c99-93b3-b886e49ffcd4"),
                            CoverImage = "",
                            CreatedBy = new Guid("75de2af9-9b4c-42f0-9f15-bd19304f4ecc"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description11",
                            DiscountPercent = 0m,
                            DiscountSold = 11000m,
                            IsDeleted = false,
                            Name = "Name11",
                            Price = 11000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 11,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("7e15374e-46f7-4281-a592-4b9ca2b3bc93"),
                            CoverImage = "",
                            CreatedBy = new Guid("08fd74b1-5cc0-4523-b9f6-c7088172edc1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description12",
                            DiscountPercent = 0m,
                            DiscountSold = 12000m,
                            IsDeleted = false,
                            Name = "Name12",
                            Price = 12000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 12,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("22a47049-d139-41bb-ba39-1719d5a82c88"),
                            CoverImage = "",
                            CreatedBy = new Guid("744a23fb-39ff-4715-b519-c58870b1798f"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description13",
                            DiscountPercent = 0m,
                            DiscountSold = 13000m,
                            IsDeleted = false,
                            Name = "Name13",
                            Price = 13000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 13,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("6a2d1ab9-0fb1-4d25-8ea9-d64b2ddbcb02"),
                            CoverImage = "",
                            CreatedBy = new Guid("db4620ed-4a5d-4e15-a352-2dae64a5759f"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description14",
                            DiscountPercent = 0m,
                            DiscountSold = 14000m,
                            IsDeleted = false,
                            Name = "Name14",
                            Price = 14000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 14,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("7781d433-1954-42af-b15a-ed002df556d4"),
                            CoverImage = "",
                            CreatedBy = new Guid("018ed0a5-70f9-4012-879d-a09f63fd6fb7"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description15",
                            DiscountPercent = 0m,
                            DiscountSold = 15000m,
                            IsDeleted = false,
                            Name = "Name15",
                            Price = 15000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 15,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("9e917dd4-74c4-49b1-8043-a01e24c6ce49"),
                            CoverImage = "",
                            CreatedBy = new Guid("aee78ef7-0def-46e0-872c-cea1680add43"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description16",
                            DiscountPercent = 0m,
                            DiscountSold = 16000m,
                            IsDeleted = false,
                            Name = "Name16",
                            Price = 16000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 16,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("452334b9-b1e3-49e0-b2a6-32006cdf1da8"),
                            CoverImage = "",
                            CreatedBy = new Guid("4683425d-a531-477d-af51-b51c71c9876d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description17",
                            DiscountPercent = 0m,
                            DiscountSold = 17000m,
                            IsDeleted = false,
                            Name = "Name17",
                            Price = 17000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 17,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("059b7ef8-d70f-4102-a42b-2c51a89baa7d"),
                            CoverImage = "",
                            CreatedBy = new Guid("267676c2-e3a3-4f24-94dd-d2d69d5535e1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description18",
                            DiscountPercent = 0m,
                            DiscountSold = 18000m,
                            IsDeleted = false,
                            Name = "Name18",
                            Price = 18000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 18,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("daf14424-161b-4733-8f83-38b662653932"),
                            CoverImage = "",
                            CreatedBy = new Guid("228bca8e-cd1b-4ff7-87df-eac56d775986"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description19",
                            DiscountPercent = 0m,
                            DiscountSold = 19000m,
                            IsDeleted = false,
                            Name = "Name19",
                            Price = 19000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 19,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("a8cee3d1-fc85-4008-b902-b734ea85c2e9"),
                            CoverImage = "",
                            CreatedBy = new Guid("5724965a-b888-4400-b5d6-ae15b6276f25"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description20",
                            DiscountPercent = 0m,
                            DiscountSold = 20000m,
                            IsDeleted = false,
                            Name = "Name20",
                            Price = 20000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 20,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("8d2c07ab-f7e8-43ec-957f-9e080f386cb5"),
                            CoverImage = "",
                            CreatedBy = new Guid("66612cfd-9f3e-4b78-9aa4-f2f3fd94d140"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description21",
                            DiscountPercent = 0m,
                            DiscountSold = 21000m,
                            IsDeleted = false,
                            Name = "Name21",
                            Price = 21000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 21,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("15fb32b6-4ba7-4b25-b489-d94f778827cf"),
                            CoverImage = "",
                            CreatedBy = new Guid("966b5c5f-fdb4-46b9-af80-17108bc7a33e"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description22",
                            DiscountPercent = 0m,
                            DiscountSold = 22000m,
                            IsDeleted = false,
                            Name = "Name22",
                            Price = 22000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 22,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("757c886a-b61a-4a9e-802a-8d855e41dbb7"),
                            CoverImage = "",
                            CreatedBy = new Guid("e5e97010-96a5-4272-a043-4169aee7175a"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description23",
                            DiscountPercent = 0m,
                            DiscountSold = 23000m,
                            IsDeleted = false,
                            Name = "Name23",
                            Price = 23000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 23,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("8942b6a2-7aed-4d75-92ad-94cfa22657c3"),
                            CoverImage = "",
                            CreatedBy = new Guid("3ac25786-8e9e-45f2-8c32-4bfeb442ccea"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description24",
                            DiscountPercent = 0m,
                            DiscountSold = 24000m,
                            IsDeleted = false,
                            Name = "Name24",
                            Price = 24000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 24,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("1073a688-c0d1-4ba7-9fe2-aa24b60d14fb"),
                            CoverImage = "",
                            CreatedBy = new Guid("bbf829de-dcfc-45e8-9f9b-e75772216a6d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description25",
                            DiscountPercent = 0m,
                            DiscountSold = 25000m,
                            IsDeleted = false,
                            Name = "Name25",
                            Price = 25000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 25,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("620df071-72ff-43cc-a956-54552448d81a"),
                            CoverImage = "",
                            CreatedBy = new Guid("4afa8e33-40b8-4182-8fdb-a1118bd0689b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description26",
                            DiscountPercent = 0m,
                            DiscountSold = 26000m,
                            IsDeleted = false,
                            Name = "Name26",
                            Price = 26000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 26,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("5cc1f3d2-826e-4bf2-b1c2-45cd6d994199"),
                            CoverImage = "",
                            CreatedBy = new Guid("351cf476-5a86-4b43-9243-5a31c99f5a26"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description27",
                            DiscountPercent = 0m,
                            DiscountSold = 27000m,
                            IsDeleted = false,
                            Name = "Name27",
                            Price = 27000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 27,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("9fef12e0-cdae-4a30-a057-595baf28b2a6"),
                            CoverImage = "",
                            CreatedBy = new Guid("f585f9c0-a53c-49a6-8b07-d3bfdf1b31a6"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description28",
                            DiscountPercent = 0m,
                            DiscountSold = 28000m,
                            IsDeleted = false,
                            Name = "Name28",
                            Price = 28000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 28,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("26d7ec30-7479-4677-b8d6-8a00b3d731dd"),
                            CoverImage = "",
                            CreatedBy = new Guid("12c840ad-c479-45cd-88ea-0df25065f2b6"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description29",
                            DiscountPercent = 0m,
                            DiscountSold = 29000m,
                            IsDeleted = false,
                            Name = "Name29",
                            Price = 29000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 29,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("1de91c95-6332-420e-961f-fa12c0f5e161"),
                            CoverImage = "",
                            CreatedBy = new Guid("3942dee4-df76-4b26-a040-e58158631869"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description30",
                            DiscountPercent = 0m,
                            DiscountSold = 30000m,
                            IsDeleted = false,
                            Name = "Name30",
                            Price = 30000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 30,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("f8889260-07ce-43e7-ac3f-6146f2308d48"),
                            CoverImage = "",
                            CreatedBy = new Guid("e0f869d4-42d2-430d-b2cf-c87289b68233"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description31",
                            DiscountPercent = 0m,
                            DiscountSold = 31000m,
                            IsDeleted = false,
                            Name = "Name31",
                            Price = 31000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 31,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("456851a1-1ac0-4021-ab6d-8f4f0f1cf121"),
                            CoverImage = "",
                            CreatedBy = new Guid("5b1d2d8e-d31b-4e53-a374-1802a8c792e5"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description32",
                            DiscountPercent = 0m,
                            DiscountSold = 32000m,
                            IsDeleted = false,
                            Name = "Name32",
                            Price = 32000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 32,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("8c761dd7-7cac-4fee-a88f-06b73f3615f4"),
                            CoverImage = "",
                            CreatedBy = new Guid("5ef9a426-52a8-4c4e-a74d-68d6d1e9fee7"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description33",
                            DiscountPercent = 0m,
                            DiscountSold = 33000m,
                            IsDeleted = false,
                            Name = "Name33",
                            Price = 33000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 33,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("b2a5a535-5f15-4b99-a697-5e4cd8234e48"),
                            CoverImage = "",
                            CreatedBy = new Guid("1f55c6ba-f57b-4b08-9e08-c54f388a677b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description34",
                            DiscountPercent = 0m,
                            DiscountSold = 34000m,
                            IsDeleted = false,
                            Name = "Name34",
                            Price = 34000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 34,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("afdec7b0-1065-48d8-bc54-f1f44b75e3d9"),
                            CoverImage = "",
                            CreatedBy = new Guid("ef6edf4e-8fb1-47de-aa69-be94912a5610"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description35",
                            DiscountPercent = 0m,
                            DiscountSold = 35000m,
                            IsDeleted = false,
                            Name = "Name35",
                            Price = 35000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 35,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("94270a02-4c08-4dae-9555-98737ed851f1"),
                            CoverImage = "",
                            CreatedBy = new Guid("af22cb60-e38f-4b02-bad3-3cf73080d086"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description36",
                            DiscountPercent = 0m,
                            DiscountSold = 36000m,
                            IsDeleted = false,
                            Name = "Name36",
                            Price = 36000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 36,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("3c1611e8-2782-4a28-80d9-52dc97d6214c"),
                            CoverImage = "",
                            CreatedBy = new Guid("5af65fcf-bc77-42a8-942b-b764b1f7a471"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description37",
                            DiscountPercent = 0m,
                            DiscountSold = 37000m,
                            IsDeleted = false,
                            Name = "Name37",
                            Price = 37000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 37,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("0c2633ed-ad73-42b3-b955-78b5376bad01"),
                            CoverImage = "",
                            CreatedBy = new Guid("6e2b94f5-7193-4bab-be3e-d1ae09dce55b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description38",
                            DiscountPercent = 0m,
                            DiscountSold = 38000m,
                            IsDeleted = false,
                            Name = "Name38",
                            Price = 38000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 38,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("47567503-e129-4e04-80b8-3383fd754fad"),
                            CoverImage = "",
                            CreatedBy = new Guid("3ac0e837-44b6-4d76-9b38-6861f191f0fc"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description39",
                            DiscountPercent = 0m,
                            DiscountSold = 39000m,
                            IsDeleted = false,
                            Name = "Name39",
                            Price = 39000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 39,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("6c2c7302-2ab5-454f-992e-1fb5644c3bbc"),
                            CoverImage = "",
                            CreatedBy = new Guid("3fe616b6-919c-45cd-a916-d711e2838226"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description40",
                            DiscountPercent = 0m,
                            DiscountSold = 40000m,
                            IsDeleted = false,
                            Name = "Name40",
                            Price = 40000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 40,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des1",
                            IsDeleted = false,
                            Name = "Cate1",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des2",
                            IsDeleted = false,
                            Name = "Cate2",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8d81bd6c-b108-4611-acee-ef78286eec24"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des3",
                            IsDeleted = false,
                            Name = "Cate3",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wait")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("VendorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Expire")
                        .HasMaxLength(20)
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1"),
                            Address = "VendorAddress1",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity1",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor1@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor1",
                            Phonenumber = "VendorPhone1",
                            Province = "VendorProvince1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2"),
                            Address = "VendorAddress2",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity2",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor2@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor2",
                            Phonenumber = "VendorPhone2",
                            Province = "VendorProvince2",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f5565937-575b-462a-903c-404727ba3765"),
                            Address = "VendorAddress3",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity3",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor3@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor3",
                            Phonenumber = "VendorPhone3",
                            Province = "VendorProvince3",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Discount", "Discount")
                        .WithMany("OrderList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany()
                        .HasForeignKey("OrderDetailFeedbackId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderDetailFeedback");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany("OrderDetailFeedbackMediaList")
                        .HasForeignKey("OrderDetailFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetailFeedback");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductList")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany("ProductList")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductDiscountList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductFeedbackList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Subscription");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserAddressList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserPaymentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetailList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Navigation("OrderDetailFeedbackMediaList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetailList");

                    b.Navigation("ProductDiscountList");

                    b.Navigation("ProductFeedbackList");

                    b.Navigation("ProductImageList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAddressList");

                    b.Navigation("UserPaymentList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
