// <auto-generated />
using System;
using Antree_Ecommerce_BE.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antree_Ecommerce_BE.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240917034021_Product Fields, Media Tables")]
    partial class ProductFieldsMediaTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.ToTable("OrderDetailFeedbackMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Expire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77561842-2bd5-4cab-b681-45e12ba8bc5c"),
                            CreatedBy = new Guid("4a9375f0-2cec-4a96-a509-023156d58502"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description0",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name0",
                            Price = 0m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 0,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("26571685-371a-49cb-975b-22da56818683"),
                            CreatedBy = new Guid("7462ceb4-0400-45b3-8aee-090da20cd216"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description1",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name1",
                            Price = 1m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 1,
                            Sold = 1,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e907d8cb-7711-4ab1-9fdd-32c4a50d7bb9"),
                            CreatedBy = new Guid("c91d8390-3869-410c-af33-81044a529453"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description2",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name2",
                            Price = 2m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 2,
                            Sold = 2,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e3ccd4ec-d2e6-48e9-9cdb-451755668cad"),
                            CreatedBy = new Guid("b3612fc8-3051-4709-89b6-23ff7caa90fd"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description3",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name3",
                            Price = 3m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 3,
                            Sold = 3,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ff69176c-d94b-4c59-83a2-c127c48a9716"),
                            CreatedBy = new Guid("ebb3d828-538a-4598-9581-2f022e0a9307"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description4",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name4",
                            Price = 4m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 4,
                            Sold = 4,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("dc2fd23b-f7a0-4f5c-b08f-b9daa28fec40"),
                            CreatedBy = new Guid("f291bf4e-f3ed-4c54-92a6-dd66484b05fe"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description5",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name5",
                            Price = 5m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 5,
                            Sold = 5,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6577bec9-c554-44c4-b1ef-970dee1f30ee"),
                            CreatedBy = new Guid("44112d8c-0075-4be4-a1b9-afccb5f08b88"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description6",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name6",
                            Price = 6m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 6,
                            Sold = 6,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("709a765e-08ce-44db-926e-b56dd1a44d1a"),
                            CreatedBy = new Guid("d66250b7-0a94-4b50-a34a-7d5b6a394c88"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description7",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name7",
                            Price = 7m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 7,
                            Sold = 7,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c7a0dcad-4951-4cd3-92d5-1273edb3f0b8"),
                            CreatedBy = new Guid("f5eb25c7-2156-4645-9e29-fc958a9e0e69"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description8",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name8",
                            Price = 8m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 8,
                            Sold = 8,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("93843421-dd98-4f3b-9c6e-481876adf258"),
                            CreatedBy = new Guid("7699500b-5c7a-47ed-96c5-55efbb4ee92c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description9",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name9",
                            Price = 9m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 9,
                            Sold = 9,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1c9d6005-420b-4c41-a77e-58e046cfea5b"),
                            CreatedBy = new Guid("c86c5e48-b62b-405b-9ed6-19c86025c9d6"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description10",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name10",
                            Price = 10m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 10,
                            Sold = 10,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("03ce518c-6671-4d9f-bdf4-242c99fcec5d"),
                            CreatedBy = new Guid("d51f7f65-57fe-4179-a67f-f8f215d28d12"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description11",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name11",
                            Price = 11m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 11,
                            Sold = 11,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1f50ad67-a7d1-479c-8e1d-9cad20147199"),
                            CreatedBy = new Guid("83d9776f-96c4-40af-870b-afcbae26ebe7"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description12",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name12",
                            Price = 12m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 12,
                            Sold = 12,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("82126b00-2cc9-4eef-9f8f-3268010eaf16"),
                            CreatedBy = new Guid("d7ae8baa-e097-485a-8525-6ae1cd2c3519"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description13",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name13",
                            Price = 13m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 13,
                            Sold = 13,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("abd42b41-2f46-43bf-b4c6-6289c3a9bf83"),
                            CreatedBy = new Guid("730eba57-da8d-404b-856f-976d082bff9d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description14",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name14",
                            Price = 14m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 14,
                            Sold = 14,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("83e647a9-37df-4add-912a-d02600279dff"),
                            CreatedBy = new Guid("9dcf59b2-ab59-472c-9c38-49c5888e5c0c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description15",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name15",
                            Price = 15m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 15,
                            Sold = 15,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cf36187c-6a60-4818-bc99-8b2245341326"),
                            CreatedBy = new Guid("42b19fdf-d811-4874-9c09-55c73b90f6a9"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description16",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name16",
                            Price = 16m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 16,
                            Sold = 16,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2250a1d7-6419-4ec8-a3ba-20e668bb848b"),
                            CreatedBy = new Guid("48cbf99b-0df4-46b3-bfa4-ffd1921c28d5"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description17",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name17",
                            Price = 17m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 17,
                            Sold = 17,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("100feeff-a7a5-4945-90ce-2e633aa8c4e2"),
                            CreatedBy = new Guid("2c6a9a6a-1d76-409a-8992-993eee55b939"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description18",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name18",
                            Price = 18m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 18,
                            Sold = 18,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8c22fc71-006a-4a4b-820c-b68d030dcd93"),
                            CreatedBy = new Guid("bdeac5aa-b2d8-49cb-b608-2560267f80bd"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description19",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name19",
                            Price = 19m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 19,
                            Sold = 19,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d67495bd-86e5-4df5-809d-0fbf9521692a"),
                            CreatedBy = new Guid("3be253c2-8213-4d55-a84d-8bcdec857906"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description20",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name20",
                            Price = 20m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 20,
                            Sold = 20,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7f1ed892-5eb4-401e-b577-d08cd3f7ffdb"),
                            CreatedBy = new Guid("e87a65a1-9d35-4729-baed-e5e821d6aa00"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description21",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name21",
                            Price = 21m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 21,
                            Sold = 21,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1ca8a14e-41ee-4b9f-8843-7d94708307ec"),
                            CreatedBy = new Guid("dd0ac4ee-a5d0-436f-bafb-3427fa7a327e"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description22",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name22",
                            Price = 22m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 22,
                            Sold = 22,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6b721afd-0b77-4e9d-a64b-14ed21114ce5"),
                            CreatedBy = new Guid("0cb329b8-7836-4be3-becc-6f27e743d19d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description23",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name23",
                            Price = 23m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 23,
                            Sold = 23,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6f330295-3e5b-4fdb-aa69-46334b06efe9"),
                            CreatedBy = new Guid("7cc374b1-7feb-4542-bbf3-a5e957a1904d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description24",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name24",
                            Price = 24m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 24,
                            Sold = 24,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6a9fe691-456e-4d00-9500-235b409d1b7e"),
                            CreatedBy = new Guid("e853dd7b-3d99-4252-824b-03f138caa827"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description25",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name25",
                            Price = 25m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 25,
                            Sold = 25,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9ec6ed90-d738-4e57-afab-9736b97d570d"),
                            CreatedBy = new Guid("e81dfa30-2a87-4cdc-b88a-2ee8ab515ced"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description26",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name26",
                            Price = 26m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 26,
                            Sold = 26,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7868dca1-c519-426c-90c8-1d1325d03f9e"),
                            CreatedBy = new Guid("825b7237-b967-468d-8047-3eba183698f1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description27",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name27",
                            Price = 27m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 27,
                            Sold = 27,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2f1bde85-bd2e-4b5f-b1b3-2eafd1ce5a2e"),
                            CreatedBy = new Guid("dedd2700-1c64-46d0-94d8-b3454791d6d0"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description28",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name28",
                            Price = 28m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 28,
                            Sold = 28,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d0ec46ee-5904-496b-95b5-7b6bec227449"),
                            CreatedBy = new Guid("683d654a-f643-484f-be24-7d669349fe59"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description29",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name29",
                            Price = 29m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 29,
                            Sold = 29,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9cfad9a6-1991-4b07-9eef-262b4d61f699"),
                            CreatedBy = new Guid("eef06ef4-f36b-4c1a-8388-5b59e4d56048"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description30",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name30",
                            Price = 30m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 30,
                            Sold = 30,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("79b64785-4f6d-4feb-8ded-00cd6dc8382f"),
                            CreatedBy = new Guid("6f6549db-bda5-49fb-9c88-35e57d6a1645"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description31",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name31",
                            Price = 31m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 31,
                            Sold = 31,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4333730f-9f6a-4e1e-81eb-39f4d4026de0"),
                            CreatedBy = new Guid("1b702c33-8460-41d1-8278-811c35ec9fc4"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description32",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name32",
                            Price = 32m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 32,
                            Sold = 32,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c986b4b9-f4ea-4b3a-83c2-77ce3e86d0b7"),
                            CreatedBy = new Guid("85a5242e-44be-4297-be8b-7f24981779a1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description33",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name33",
                            Price = 33m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 33,
                            Sold = 33,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b6fcd825-601a-454b-8df6-0a309f45760f"),
                            CreatedBy = new Guid("86634a78-d0a2-4369-9960-1e4e615964de"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description34",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name34",
                            Price = 34m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 34,
                            Sold = 34,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7d97ea60-2ad3-443f-a127-adbded02786d"),
                            CreatedBy = new Guid("95c57bc6-48b3-4ca4-8340-9c9ff4cbd124"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description35",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name35",
                            Price = 35m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 35,
                            Sold = 35,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c3f5de65-866a-4e7d-b864-b9ad2649f731"),
                            CreatedBy = new Guid("77512fe4-5e32-4b31-91ba-e228efe63374"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description36",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name36",
                            Price = 36m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 36,
                            Sold = 36,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e3e03ee0-4650-4c09-a6ea-6f3c831a7709"),
                            CreatedBy = new Guid("609b6141-3ecc-4be9-ba4f-0badcb52599f"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description37",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name37",
                            Price = 37m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 37,
                            Sold = 37,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7263ac58-402b-4cb8-b46d-7747cf73eba3"),
                            CreatedBy = new Guid("26b17607-0bb6-412c-a4c0-9e47618e88ea"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description38",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name38",
                            Price = 38m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 38,
                            Sold = 38,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9ce7f16c-88d7-46c3-8fd9-3cdc210f4e25"),
                            CreatedBy = new Guid("ae8c89fd-d949-46c5-90e7-aba26ecb0e53"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description39",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name39",
                            Price = 39m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 39,
                            Sold = 39,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("365a149d-2b6f-47c4-bdaf-df47a54c3987"),
                            CreatedBy = new Guid("1bd8d0f0-b687-4f15-bc64-2033ea54f75d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description40",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name40",
                            Price = 40m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 40,
                            Sold = 40,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des1",
                            IsDeleted = false,
                            Name = "Cate1",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des2",
                            IsDeleted = false,
                            Name = "Cate2",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8d81bd6c-b108-4611-acee-ef78286eec24"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des3",
                            IsDeleted = false,
                            Name = "Cate3",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Expire")
                        .HasMaxLength(20)
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Discount", "Discount")
                        .WithMany("OrderList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany()
                        .HasForeignKey("OrderDetailFeedbackId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderDetailFeedback");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany("OrderDetailFeedbackMediaList")
                        .HasForeignKey("OrderDetailFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetailFeedback");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductList")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductDiscountList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductFeedbackList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserAddressList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserPaymentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetailList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Navigation("OrderDetailFeedbackMediaList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetailList");

                    b.Navigation("ProductDiscountList");

                    b.Navigation("ProductFeedbackList");

                    b.Navigation("ProductImageList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAddressList");

                    b.Navigation("UserPaymentList");
                });
#pragma warning restore 612, 618
        }
    }
}
