// <auto-generated />
using System;
using Antree_Ecommerce_BE.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antree_Ecommerce_BE.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021210149_TransactionTable")]
    partial class TransactionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeedback")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductPriceDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.ToTable("OrderDetailFeedbackMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Expire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfbf943c-1873-4a40-ba53-6260a3dfe6cc"),
                            CoverImage = "",
                            CreatedBy = new Guid("f7654475-ee31-4574-ac96-84c08ef21c81"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description0",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name0",
                            Price = 0m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 0,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("b099b093-0e43-487c-a032-e1ef457550cd"),
                            CoverImage = "",
                            CreatedBy = new Guid("b3756c5d-0a80-447e-b0ff-62f2006e0eef"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description1",
                            DiscountPercent = 0m,
                            DiscountSold = 1000m,
                            IsDeleted = false,
                            Name = "Name1",
                            Price = 1000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 1,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("bd6597bb-6b86-4a2e-8db8-e97738faa85a"),
                            CoverImage = "",
                            CreatedBy = new Guid("2cb78d52-2748-4c87-b662-ce56de1eeafa"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description2",
                            DiscountPercent = 0m,
                            DiscountSold = 2000m,
                            IsDeleted = false,
                            Name = "Name2",
                            Price = 2000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 2,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("f9fdc4c7-e788-4fc9-9040-7abdfe90af02"),
                            CoverImage = "",
                            CreatedBy = new Guid("12b42d69-2e8f-4e00-b889-9c4c83cb0e22"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description3",
                            DiscountPercent = 0m,
                            DiscountSold = 3000m,
                            IsDeleted = false,
                            Name = "Name3",
                            Price = 3000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 3,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("54e7c36e-7ea3-4c53-9c73-529fee6da613"),
                            CoverImage = "",
                            CreatedBy = new Guid("353834ee-2952-40d0-af3e-88ff8bd75cca"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description4",
                            DiscountPercent = 0m,
                            DiscountSold = 4000m,
                            IsDeleted = false,
                            Name = "Name4",
                            Price = 4000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 4,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("76ed6d1d-d2d0-498d-9bdb-c301827a7859"),
                            CoverImage = "",
                            CreatedBy = new Guid("aa463bb3-9695-4ac6-81d7-ee7321451610"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description5",
                            DiscountPercent = 0m,
                            DiscountSold = 5000m,
                            IsDeleted = false,
                            Name = "Name5",
                            Price = 5000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 5,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("9199304e-937f-458f-83aa-de494089a872"),
                            CoverImage = "",
                            CreatedBy = new Guid("7258fabf-026f-4f48-aebe-53a5160fa432"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description6",
                            DiscountPercent = 0m,
                            DiscountSold = 6000m,
                            IsDeleted = false,
                            Name = "Name6",
                            Price = 6000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 6,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("300a3d1d-fab9-4e3b-87c1-e320e2ad5430"),
                            CoverImage = "",
                            CreatedBy = new Guid("3f94a0d2-ebed-4b6b-bc89-65d428a53577"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description7",
                            DiscountPercent = 0m,
                            DiscountSold = 7000m,
                            IsDeleted = false,
                            Name = "Name7",
                            Price = 7000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 7,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("bd9ed5ed-419d-4b31-8baf-af81512d1f34"),
                            CoverImage = "",
                            CreatedBy = new Guid("1f5d5810-e2f8-4f8e-b812-f85575734a05"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description8",
                            DiscountPercent = 0m,
                            DiscountSold = 8000m,
                            IsDeleted = false,
                            Name = "Name8",
                            Price = 8000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 8,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("1d09fe4e-7646-4df5-96ba-8cca4200f81c"),
                            CoverImage = "",
                            CreatedBy = new Guid("76e1c270-23ae-497a-8137-23eca63c841f"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description9",
                            DiscountPercent = 0m,
                            DiscountSold = 9000m,
                            IsDeleted = false,
                            Name = "Name9",
                            Price = 9000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 9,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("edfa3409-88a7-46fa-9641-27020ae2efcb"),
                            CoverImage = "",
                            CreatedBy = new Guid("868f3b4c-9540-44dc-b6eb-f6c6630baf04"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description10",
                            DiscountPercent = 0m,
                            DiscountSold = 10000m,
                            IsDeleted = false,
                            Name = "Name10",
                            Price = 10000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 10,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("34b8dd1d-2f8b-4a7e-9fcb-5fead1e57928"),
                            CoverImage = "",
                            CreatedBy = new Guid("a932c5a4-fc43-4eba-a294-ed8eb7e9c232"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description11",
                            DiscountPercent = 0m,
                            DiscountSold = 11000m,
                            IsDeleted = false,
                            Name = "Name11",
                            Price = 11000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 11,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("e8e2afc9-d2f1-4c1a-beda-e84184dc08f3"),
                            CoverImage = "",
                            CreatedBy = new Guid("f7e2308d-99a4-4120-bd54-2b26ebe538c3"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description12",
                            DiscountPercent = 0m,
                            DiscountSold = 12000m,
                            IsDeleted = false,
                            Name = "Name12",
                            Price = 12000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 12,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("33c730dd-b204-4db3-ba06-0e08ec4b8307"),
                            CoverImage = "",
                            CreatedBy = new Guid("44dcd4f7-e7b4-4486-9231-b78a00329c16"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description13",
                            DiscountPercent = 0m,
                            DiscountSold = 13000m,
                            IsDeleted = false,
                            Name = "Name13",
                            Price = 13000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 13,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("f1d75a56-7457-4280-8062-d7dd54166f14"),
                            CoverImage = "",
                            CreatedBy = new Guid("ad6796db-f041-4d1c-a2a5-49ef98550f32"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description14",
                            DiscountPercent = 0m,
                            DiscountSold = 14000m,
                            IsDeleted = false,
                            Name = "Name14",
                            Price = 14000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 14,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("50da51d7-c286-4fb4-97ce-b243cb2a53a8"),
                            CoverImage = "",
                            CreatedBy = new Guid("3726eb6e-960f-4fab-9dab-786f3850f841"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description15",
                            DiscountPercent = 0m,
                            DiscountSold = 15000m,
                            IsDeleted = false,
                            Name = "Name15",
                            Price = 15000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 15,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("ffe7b87a-7ea5-468d-b5f9-dcb970a90434"),
                            CoverImage = "",
                            CreatedBy = new Guid("93ef4861-00e7-4df6-89d4-ae678a655bf4"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description16",
                            DiscountPercent = 0m,
                            DiscountSold = 16000m,
                            IsDeleted = false,
                            Name = "Name16",
                            Price = 16000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 16,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("645f005f-63de-44cb-8efc-a522373631a4"),
                            CoverImage = "",
                            CreatedBy = new Guid("13d96a06-c6c6-45a3-a4d6-c12e85fb3e44"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description17",
                            DiscountPercent = 0m,
                            DiscountSold = 17000m,
                            IsDeleted = false,
                            Name = "Name17",
                            Price = 17000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 17,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("13bf9dd3-d8f8-401f-8c08-601e9fa34ae0"),
                            CoverImage = "",
                            CreatedBy = new Guid("86d4d200-1b0f-4b42-a0e4-20c0a568c156"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description18",
                            DiscountPercent = 0m,
                            DiscountSold = 18000m,
                            IsDeleted = false,
                            Name = "Name18",
                            Price = 18000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 18,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("083961c4-3265-4f32-970f-e3f4323da29f"),
                            CoverImage = "",
                            CreatedBy = new Guid("d7495c60-e848-4bc8-8d6e-19aa57f18eda"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description19",
                            DiscountPercent = 0m,
                            DiscountSold = 19000m,
                            IsDeleted = false,
                            Name = "Name19",
                            Price = 19000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 19,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("39ac6509-d0f1-41ce-bbdf-0a04cc95d129"),
                            CoverImage = "",
                            CreatedBy = new Guid("2949a011-8500-4082-8b4d-9c5ec5081f52"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description20",
                            DiscountPercent = 0m,
                            DiscountSold = 20000m,
                            IsDeleted = false,
                            Name = "Name20",
                            Price = 20000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 20,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("76ac8631-69fa-4b2a-adc1-83d5cddbeaa6"),
                            CoverImage = "",
                            CreatedBy = new Guid("517ca369-a87a-444d-8e4f-ccd69f835985"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description21",
                            DiscountPercent = 0m,
                            DiscountSold = 21000m,
                            IsDeleted = false,
                            Name = "Name21",
                            Price = 21000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 21,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("a0d79dbf-4d1b-4535-961e-101eb5b64639"),
                            CoverImage = "",
                            CreatedBy = new Guid("ac35eeb2-89a5-4d12-9dd7-beb90ca99b0c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description22",
                            DiscountPercent = 0m,
                            DiscountSold = 22000m,
                            IsDeleted = false,
                            Name = "Name22",
                            Price = 22000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 22,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("f8e06597-00ab-456d-925f-232b4ffdb7d6"),
                            CoverImage = "",
                            CreatedBy = new Guid("641b7d4d-aaeb-4a48-b1b4-0b25013d50cf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description23",
                            DiscountPercent = 0m,
                            DiscountSold = 23000m,
                            IsDeleted = false,
                            Name = "Name23",
                            Price = 23000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 23,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("076b0d49-ee98-45aa-a900-a263e9233fbe"),
                            CoverImage = "",
                            CreatedBy = new Guid("f1d9e2b6-8ba2-485a-813d-6ad82c707346"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description24",
                            DiscountPercent = 0m,
                            DiscountSold = 24000m,
                            IsDeleted = false,
                            Name = "Name24",
                            Price = 24000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 24,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("1d9c7bf9-6e33-4951-8d9f-8ca1e83bb34a"),
                            CoverImage = "",
                            CreatedBy = new Guid("a15688a6-3a53-45ae-b397-b8fb1f08e17d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description25",
                            DiscountPercent = 0m,
                            DiscountSold = 25000m,
                            IsDeleted = false,
                            Name = "Name25",
                            Price = 25000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 25,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("9b4ebade-04ac-4845-bbbb-9f797b4fe252"),
                            CoverImage = "",
                            CreatedBy = new Guid("555e5442-0d26-4eee-9587-bf2a80d57ca7"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description26",
                            DiscountPercent = 0m,
                            DiscountSold = 26000m,
                            IsDeleted = false,
                            Name = "Name26",
                            Price = 26000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 26,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("3a785ee1-63fe-447b-9a3e-0bf7a37d0709"),
                            CoverImage = "",
                            CreatedBy = new Guid("594b3f50-a019-41f7-aaf6-89f0889bae5f"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description27",
                            DiscountPercent = 0m,
                            DiscountSold = 27000m,
                            IsDeleted = false,
                            Name = "Name27",
                            Price = 27000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 27,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("aaff4e13-ca51-4ee0-87f6-7b641c40fb18"),
                            CoverImage = "",
                            CreatedBy = new Guid("ff85a7bf-11c7-4ae5-8be0-9a261fe1d4da"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description28",
                            DiscountPercent = 0m,
                            DiscountSold = 28000m,
                            IsDeleted = false,
                            Name = "Name28",
                            Price = 28000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 28,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("4fbdb1ef-22f7-4bce-950b-f09f1196efdd"),
                            CoverImage = "",
                            CreatedBy = new Guid("e700382a-e25e-4e02-a522-610628a32c15"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description29",
                            DiscountPercent = 0m,
                            DiscountSold = 29000m,
                            IsDeleted = false,
                            Name = "Name29",
                            Price = 29000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 29,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("8af86a05-1a76-4c56-9689-0db2ca05e9cc"),
                            CoverImage = "",
                            CreatedBy = new Guid("e4201efa-760e-4ddb-8a53-6ef9a862b1d1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description30",
                            DiscountPercent = 0m,
                            DiscountSold = 30000m,
                            IsDeleted = false,
                            Name = "Name30",
                            Price = 30000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 30,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("4b9f3540-0621-489a-8654-422b3bcfcd07"),
                            CoverImage = "",
                            CreatedBy = new Guid("54aa4272-0def-4d11-a4bc-f404850e71ea"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description31",
                            DiscountPercent = 0m,
                            DiscountSold = 31000m,
                            IsDeleted = false,
                            Name = "Name31",
                            Price = 31000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 31,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("2cfaa0c6-0028-4969-a5fc-8cd9e4b662cd"),
                            CoverImage = "",
                            CreatedBy = new Guid("7caccd9f-e63b-4ffd-b265-bd20f0217b61"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description32",
                            DiscountPercent = 0m,
                            DiscountSold = 32000m,
                            IsDeleted = false,
                            Name = "Name32",
                            Price = 32000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 32,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("c2d6bc2d-e1dd-487a-9d14-69741274878b"),
                            CoverImage = "",
                            CreatedBy = new Guid("aa4a3805-1b45-4505-ab23-ecdcb0bfad04"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description33",
                            DiscountPercent = 0m,
                            DiscountSold = 33000m,
                            IsDeleted = false,
                            Name = "Name33",
                            Price = 33000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 33,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("5c932d34-35f9-400b-95ee-3f921bffff7b"),
                            CoverImage = "",
                            CreatedBy = new Guid("ac4cb5e0-7c00-4211-a2d7-4a9d3ac03cb5"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description34",
                            DiscountPercent = 0m,
                            DiscountSold = 34000m,
                            IsDeleted = false,
                            Name = "Name34",
                            Price = 34000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 34,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("fd9f36bf-36bb-477c-a579-abaed583caed"),
                            CoverImage = "",
                            CreatedBy = new Guid("1ef4a3d6-5d87-4bfd-89b1-6f987423e392"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description35",
                            DiscountPercent = 0m,
                            DiscountSold = 35000m,
                            IsDeleted = false,
                            Name = "Name35",
                            Price = 35000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 35,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("3f8f5804-9fc5-40a6-9962-1a451f8ad892"),
                            CoverImage = "",
                            CreatedBy = new Guid("55aa42b5-bf06-4903-bba5-e18215ee2de4"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description36",
                            DiscountPercent = 0m,
                            DiscountSold = 36000m,
                            IsDeleted = false,
                            Name = "Name36",
                            Price = 36000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 36,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("ba9982b2-2769-4060-980a-84ac7c8c76de"),
                            CoverImage = "",
                            CreatedBy = new Guid("e45dd332-523e-4119-9feb-565a037e522c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description37",
                            DiscountPercent = 0m,
                            DiscountSold = 37000m,
                            IsDeleted = false,
                            Name = "Name37",
                            Price = 37000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 37,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("bc5f7f9b-4b4e-4dd7-abf2-e01fac225102"),
                            CoverImage = "",
                            CreatedBy = new Guid("f1d693a6-0673-46af-9a42-bea5fa0ba367"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description38",
                            DiscountPercent = 0m,
                            DiscountSold = 38000m,
                            IsDeleted = false,
                            Name = "Name38",
                            Price = 38000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 38,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("f8db2be6-9811-4ab3-9a6d-5c110f75f34f"),
                            CoverImage = "",
                            CreatedBy = new Guid("9f8d35c5-adb6-49e5-87b1-a40f5bd4a145"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description39",
                            DiscountPercent = 0m,
                            DiscountSold = 39000m,
                            IsDeleted = false,
                            Name = "Name39",
                            Price = 39000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 39,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("e5af5517-1cf4-4da7-b9d5-3d513ab8b9c6"),
                            CoverImage = "",
                            CreatedBy = new Guid("e16f2cd9-1c48-4348-a07a-063a6a30f712"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description40",
                            DiscountPercent = 0m,
                            DiscountSold = 40000m,
                            IsDeleted = false,
                            Name = "Name40",
                            Price = 40000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 40,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des1",
                            IsDeleted = false,
                            Name = "Cate1",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des2",
                            IsDeleted = false,
                            Name = "Cate2",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8d81bd6c-b108-4611-acee-ef78286eec24"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des3",
                            IsDeleted = false,
                            Name = "Cate3",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wait")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("VendorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Expire")
                        .HasMaxLength(20)
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1"),
                            Address = "VendorAddress1",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity1",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor1@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor1",
                            Phonenumber = "VendorPhone1",
                            Province = "VendorProvince1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2"),
                            Address = "VendorAddress2",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity2",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor2@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor2",
                            Phonenumber = "VendorPhone2",
                            Province = "VendorProvince2",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f5565937-575b-462a-903c-404727ba3765"),
                            Address = "VendorAddress3",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity3",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor3@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor3",
                            Phonenumber = "VendorPhone3",
                            Province = "VendorProvince3",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Discount", "Discount")
                        .WithMany("OrderList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany()
                        .HasForeignKey("OrderDetailFeedbackId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderDetailFeedback");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany("OrderDetailFeedbackMediaList")
                        .HasForeignKey("OrderDetailFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetailFeedback");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductList")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany("ProductList")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductDiscountList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductFeedbackList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Subscription");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserAddressList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserPaymentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetailList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Navigation("OrderDetailFeedbackMediaList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetailList");

                    b.Navigation("ProductDiscountList");

                    b.Navigation("ProductFeedbackList");

                    b.Navigation("ProductImageList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAddressList");

                    b.Navigation("UserPaymentList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
