// <auto-generated />
using System;
using Antree_Ecommerce_BE.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antree_Ecommerce_BE.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021202524_NewSubscriptionTable")]
    partial class NewSubscriptionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeedback")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductPriceDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderDetailFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailFeedbackId");

                    b.ToTable("OrderDetailFeedbackMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Expire")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("659c3b80-62c4-45ce-a441-bd08c5980b12"),
                            CoverImage = "",
                            CreatedBy = new Guid("9e8dee4a-34ec-4c2e-ae84-769c55abea99"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description0",
                            DiscountPercent = 0m,
                            DiscountSold = 0m,
                            IsDeleted = false,
                            Name = "Name0",
                            Price = 0m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 0,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("a910198b-ff75-41eb-8c6c-7bac8abe3d61"),
                            CoverImage = "",
                            CreatedBy = new Guid("9daebede-29bf-447f-beba-82aef24096a1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description1",
                            DiscountPercent = 0m,
                            DiscountSold = 1000m,
                            IsDeleted = false,
                            Name = "Name1",
                            Price = 1000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 1,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("66fd80e4-c1ca-4d76-b365-24cf1024f65c"),
                            CoverImage = "",
                            CreatedBy = new Guid("9665aaa6-5177-49c3-8810-60b44bf56225"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description2",
                            DiscountPercent = 0m,
                            DiscountSold = 2000m,
                            IsDeleted = false,
                            Name = "Name2",
                            Price = 2000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 2,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("4db6940b-d4e4-40e0-9b67-83b21876225a"),
                            CoverImage = "",
                            CreatedBy = new Guid("70f70617-81e0-435f-9af5-a2310d9072a5"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description3",
                            DiscountPercent = 0m,
                            DiscountSold = 3000m,
                            IsDeleted = false,
                            Name = "Name3",
                            Price = 3000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 3,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("8b6c38d0-1b0c-4543-bd5b-294652b5669f"),
                            CoverImage = "",
                            CreatedBy = new Guid("257e7c7c-faeb-48f6-9cd4-58619e7a7df7"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description4",
                            DiscountPercent = 0m,
                            DiscountSold = 4000m,
                            IsDeleted = false,
                            Name = "Name4",
                            Price = 4000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 4,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("ffbef7f7-6786-4a3c-9268-3151aad17ae8"),
                            CoverImage = "",
                            CreatedBy = new Guid("b67f6429-9bb2-45db-adc5-e9ba912e3e52"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description5",
                            DiscountPercent = 0m,
                            DiscountSold = 5000m,
                            IsDeleted = false,
                            Name = "Name5",
                            Price = 5000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 5,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("93eeb3a8-a724-451c-ae3d-b2dc10e69c35"),
                            CoverImage = "",
                            CreatedBy = new Guid("27d16087-f8d6-4cf9-8ac7-88131e564e38"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description6",
                            DiscountPercent = 0m,
                            DiscountSold = 6000m,
                            IsDeleted = false,
                            Name = "Name6",
                            Price = 6000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 6,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("4259a7b0-15ef-49f1-b241-7e80eecad696"),
                            CoverImage = "",
                            CreatedBy = new Guid("617a7c8d-5a87-4cbb-820c-4755603afad1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description7",
                            DiscountPercent = 0m,
                            DiscountSold = 7000m,
                            IsDeleted = false,
                            Name = "Name7",
                            Price = 7000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 7,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("b9d369e4-69cf-4c81-a3a6-6d89b532be8d"),
                            CoverImage = "",
                            CreatedBy = new Guid("4c229b21-545d-4c1e-b354-dcd0b4712741"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description8",
                            DiscountPercent = 0m,
                            DiscountSold = 8000m,
                            IsDeleted = false,
                            Name = "Name8",
                            Price = 8000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 8,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("e896c95d-0dd2-4b43-8c48-4d4cf1e06426"),
                            CoverImage = "",
                            CreatedBy = new Guid("08955964-7a7a-423c-9792-a4623b2c4484"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description9",
                            DiscountPercent = 0m,
                            DiscountSold = 9000m,
                            IsDeleted = false,
                            Name = "Name9",
                            Price = 9000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 9,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("97e5efc1-c5a9-46ee-9d73-dcdb9122dcd7"),
                            CoverImage = "",
                            CreatedBy = new Guid("10479857-abb9-4299-b5af-3107d6eb6579"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description10",
                            DiscountPercent = 0m,
                            DiscountSold = 10000m,
                            IsDeleted = false,
                            Name = "Name10",
                            Price = 10000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 10,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("02857203-5cee-489e-a509-c25e21ec89b5"),
                            CoverImage = "",
                            CreatedBy = new Guid("a26f71ca-ff64-46e0-98ec-645c549c55a9"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description11",
                            DiscountPercent = 0m,
                            DiscountSold = 11000m,
                            IsDeleted = false,
                            Name = "Name11",
                            Price = 11000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 11,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("e5bd4485-4be7-4e3f-bc3a-a1b421fea0cd"),
                            CoverImage = "",
                            CreatedBy = new Guid("0c15632a-d90c-4418-9a41-6ece8b6cd664"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description12",
                            DiscountPercent = 0m,
                            DiscountSold = 12000m,
                            IsDeleted = false,
                            Name = "Name12",
                            Price = 12000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 12,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("58414f6b-a90f-4eae-bd35-0bd1e9abcbee"),
                            CoverImage = "",
                            CreatedBy = new Guid("8f3b842b-a0cb-4e12-9285-63b1a87e6166"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description13",
                            DiscountPercent = 0m,
                            DiscountSold = 13000m,
                            IsDeleted = false,
                            Name = "Name13",
                            Price = 13000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 13,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("2e209149-4a19-4c3f-8532-50dbcb833972"),
                            CoverImage = "",
                            CreatedBy = new Guid("146bac0c-39af-4c26-a509-796e910bf074"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description14",
                            DiscountPercent = 0m,
                            DiscountSold = 14000m,
                            IsDeleted = false,
                            Name = "Name14",
                            Price = 14000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 14,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("af416424-87eb-4909-9512-e8c3c33804aa"),
                            CoverImage = "",
                            CreatedBy = new Guid("0672e255-78c5-4b01-bb83-3b79a2e2b36e"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description15",
                            DiscountPercent = 0m,
                            DiscountSold = 15000m,
                            IsDeleted = false,
                            Name = "Name15",
                            Price = 15000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 15,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("55fd3c19-4945-4f9a-a268-f23bd3ec98e3"),
                            CoverImage = "",
                            CreatedBy = new Guid("bfb38e48-ea04-4288-9ba0-0e19ae28ccc1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description16",
                            DiscountPercent = 0m,
                            DiscountSold = 16000m,
                            IsDeleted = false,
                            Name = "Name16",
                            Price = 16000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 16,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("377a64c7-09e1-4fe4-bd8e-95e0c7968d9e"),
                            CoverImage = "",
                            CreatedBy = new Guid("f2bc70ae-2051-46b3-903c-996ec24731e0"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description17",
                            DiscountPercent = 0m,
                            DiscountSold = 17000m,
                            IsDeleted = false,
                            Name = "Name17",
                            Price = 17000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 17,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("994d6fd3-23a1-41d6-be49-fc0329d983b3"),
                            CoverImage = "",
                            CreatedBy = new Guid("2333a3c4-7c18-43a8-979b-13a7348bae00"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description18",
                            DiscountPercent = 0m,
                            DiscountSold = 18000m,
                            IsDeleted = false,
                            Name = "Name18",
                            Price = 18000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 18,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("ffe74f1d-6d3c-4499-9b51-94c3dffcf252"),
                            CoverImage = "",
                            CreatedBy = new Guid("dfbed439-2be9-466c-b59e-a70995ce0163"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description19",
                            DiscountPercent = 0m,
                            DiscountSold = 19000m,
                            IsDeleted = false,
                            Name = "Name19",
                            Price = 19000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 19,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("d7ac1145-f438-4402-ac7d-0ef2d9358155"),
                            CoverImage = "",
                            CreatedBy = new Guid("5cc82f35-66d3-42f5-84aa-88ad29241e48"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description20",
                            DiscountPercent = 0m,
                            DiscountSold = 20000m,
                            IsDeleted = false,
                            Name = "Name20",
                            Price = 20000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 20,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("24538206-c743-44eb-a2b4-12415a551f6f"),
                            CoverImage = "",
                            CreatedBy = new Guid("e14f0f27-6f7e-4425-a231-7370db1ff8e9"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description21",
                            DiscountPercent = 0m,
                            DiscountSold = 21000m,
                            IsDeleted = false,
                            Name = "Name21",
                            Price = 21000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 21,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("15f4e766-6a02-4357-9f51-557447e7811f"),
                            CoverImage = "",
                            CreatedBy = new Guid("44557aa3-d4e8-4a42-8323-64b74751c3a0"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description22",
                            DiscountPercent = 0m,
                            DiscountSold = 22000m,
                            IsDeleted = false,
                            Name = "Name22",
                            Price = 22000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 22,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("31297ea1-f351-4b84-8fbb-5cd1bb783fee"),
                            CoverImage = "",
                            CreatedBy = new Guid("2db59bec-472a-4f12-bdab-f86bafbe3d42"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description23",
                            DiscountPercent = 0m,
                            DiscountSold = 23000m,
                            IsDeleted = false,
                            Name = "Name23",
                            Price = 23000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 23,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("cc09f14f-660d-4f82-8162-369707494bca"),
                            CoverImage = "",
                            CreatedBy = new Guid("c786df3b-4a12-4e33-8067-12cb54bd031c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description24",
                            DiscountPercent = 0m,
                            DiscountSold = 24000m,
                            IsDeleted = false,
                            Name = "Name24",
                            Price = 24000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 24,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("aac5933c-0c62-467a-a983-5e7dcda595a4"),
                            CoverImage = "",
                            CreatedBy = new Guid("e4adb88c-0086-49fa-a402-22022b69000b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description25",
                            DiscountPercent = 0m,
                            DiscountSold = 25000m,
                            IsDeleted = false,
                            Name = "Name25",
                            Price = 25000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 25,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("4e63f15a-f92a-4aeb-836d-c33d96fe8745"),
                            CoverImage = "",
                            CreatedBy = new Guid("e6a57b9f-01ab-4c0b-8534-207bbe15449e"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description26",
                            DiscountPercent = 0m,
                            DiscountSold = 26000m,
                            IsDeleted = false,
                            Name = "Name26",
                            Price = 26000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 26,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("39cdc74d-e193-4ec1-b9b4-46d477d09769"),
                            CoverImage = "",
                            CreatedBy = new Guid("35654ea8-68fb-49b2-a2c0-9ec01fecd44b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description27",
                            DiscountPercent = 0m,
                            DiscountSold = 27000m,
                            IsDeleted = false,
                            Name = "Name27",
                            Price = 27000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 27,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("fbd207bd-3106-4bd2-8dc1-ec3e7bb7ad10"),
                            CoverImage = "",
                            CreatedBy = new Guid("4f9c7a9f-ab7c-47a9-b04f-cb903850d48d"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description28",
                            DiscountPercent = 0m,
                            DiscountSold = 28000m,
                            IsDeleted = false,
                            Name = "Name28",
                            Price = 28000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 28,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("11e113c4-1c13-43a5-9d04-8a8ac75afee6"),
                            CoverImage = "",
                            CreatedBy = new Guid("4e30bd84-54c9-475b-8c0d-cee069b0f33c"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description29",
                            DiscountPercent = 0m,
                            DiscountSold = 29000m,
                            IsDeleted = false,
                            Name = "Name29",
                            Price = 29000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 29,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("d85b98d9-3165-4086-a00f-6f549048ef1d"),
                            CoverImage = "",
                            CreatedBy = new Guid("607c5927-1c2a-4472-899e-09095ddb49d1"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description30",
                            DiscountPercent = 0m,
                            DiscountSold = 30000m,
                            IsDeleted = false,
                            Name = "Name30",
                            Price = 30000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 30,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("965c4c51-3d4d-4d4e-889e-52d653cf9c7c"),
                            CoverImage = "",
                            CreatedBy = new Guid("03f6175b-3fdc-4de6-a137-6a7d8a1d7c43"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description31",
                            DiscountPercent = 0m,
                            DiscountSold = 31000m,
                            IsDeleted = false,
                            Name = "Name31",
                            Price = 31000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 31,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("4e7df899-f545-4b41-99ab-38971514b955"),
                            CoverImage = "",
                            CreatedBy = new Guid("04c53369-a4cb-48ea-8964-7e537d5f9d80"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description32",
                            DiscountPercent = 0m,
                            DiscountSold = 32000m,
                            IsDeleted = false,
                            Name = "Name32",
                            Price = 32000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 32,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("49c95ea3-3f57-4831-a7d2-f26429f607ba"),
                            CoverImage = "",
                            CreatedBy = new Guid("d713f69f-82f7-4a21-9dc1-b428d37a7844"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description33",
                            DiscountPercent = 0m,
                            DiscountSold = 33000m,
                            IsDeleted = false,
                            Name = "Name33",
                            Price = 33000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 33,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("c819c811-5eae-4b74-9994-16791ac90144"),
                            CoverImage = "",
                            CreatedBy = new Guid("2e9c2a4f-7fcc-4858-8c49-03a0e3db9d39"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description34",
                            DiscountPercent = 0m,
                            DiscountSold = 34000m,
                            IsDeleted = false,
                            Name = "Name34",
                            Price = 34000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 34,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("1f4f6216-b952-432a-aa8a-fdf4fefe55cc"),
                            CoverImage = "",
                            CreatedBy = new Guid("9a1ece7c-c887-44ed-a6a7-44435fb695bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description35",
                            DiscountPercent = 0m,
                            DiscountSold = 35000m,
                            IsDeleted = false,
                            Name = "Name35",
                            Price = 35000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 35,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("71038ce1-b337-4db2-affa-6fa98b32f004"),
                            CoverImage = "",
                            CreatedBy = new Guid("96a7947f-de60-43d5-9c2b-f40e7fd36ca3"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description36",
                            DiscountPercent = 0m,
                            DiscountSold = 36000m,
                            IsDeleted = false,
                            Name = "Name36",
                            Price = 36000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 36,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("a87a8944-5493-4d66-b147-5408be2a214f"),
                            CoverImage = "",
                            CreatedBy = new Guid("127ce6f1-d4be-47a1-b365-1d6bb2ecd6f8"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description37",
                            DiscountPercent = 0m,
                            DiscountSold = 37000m,
                            IsDeleted = false,
                            Name = "Name37",
                            Price = 37000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 37,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("c59312e9-ae91-4972-ac62-00a7e2d5f4d3"),
                            CoverImage = "",
                            CreatedBy = new Guid("1ea604fc-98eb-4700-bdd4-80597ef8071b"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description38",
                            DiscountPercent = 0m,
                            DiscountSold = 38000m,
                            IsDeleted = false,
                            Name = "Name38",
                            Price = 38000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 38,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        },
                        new
                        {
                            Id = new Guid("87bc6764-c8a7-4abd-a746-2bfd094fd05a"),
                            CoverImage = "",
                            CreatedBy = new Guid("dc1978eb-35ce-4723-b2b1-65dde103d2a8"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description39",
                            DiscountPercent = 0m,
                            DiscountSold = 39000m,
                            IsDeleted = false,
                            Name = "Name39",
                            Price = 39000m,
                            ProductCategoryId = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            Sku = 39,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2")
                        },
                        new
                        {
                            Id = new Guid("379e86d4-715a-4df3-a027-fdc055c32a38"),
                            CoverImage = "",
                            CreatedBy = new Guid("3d31a860-59cf-46bb-875f-db43dddc2328"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description40",
                            DiscountPercent = 0m,
                            DiscountSold = 40000m,
                            IsDeleted = false,
                            Name = "Name40",
                            Price = 40000m,
                            ProductCategoryId = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            Sku = 40,
                            Sold = 0,
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorId = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26df3c94-715f-4048-a96a-04a6e80bbd15"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des1",
                            IsDeleted = false,
                            Name = "Cate1",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("acc02cc0-825a-4453-b923-e6ae7f4007a4"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des2",
                            IsDeleted = false,
                            Name = "Cate2",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8d81bd6c-b108-4611-acee-ef78286eec24"),
                            CreatedBy = new Guid("2cd8a571-f443-4623-97dd-c8d4a41a80bf"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Des3",
                            IsDeleted = false,
                            Name = "Cate3",
                            UpdatedBy = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscount", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeedback", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMedia", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wait")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("VendorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Cvc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Expire")
                        .HasMaxLength(20)
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrder")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayment", (string)null);
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ef2d83-48fd-41ea-952b-c3803a59b2c1"),
                            Address = "VendorAddress1",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity1",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor1@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor1",
                            Phonenumber = "VendorPhone1",
                            Province = "VendorProvince1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d5ab34c8-d8ce-4e30-9446-13735a334ef2"),
                            Address = "VendorAddress2",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity2",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor2@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor2",
                            Phonenumber = "VendorPhone2",
                            Province = "VendorProvince2",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f5565937-575b-462a-903c-404727ba3765"),
                            Address = "VendorAddress3",
                            AvatarImage = "123",
                            BankAccountNumber = "123",
                            BankName = "123",
                            BankOwnerName = "123",
                            City = "VendorCity3",
                            CoverImage = "123",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOnUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Vendor3@gmail.com",
                            IsDeleted = false,
                            Name = "Vendor3",
                            Phonenumber = "VendorPhone3",
                            Province = "VendorProvince3",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Discount", "Discount")
                        .WithMany("OrderList")
                        .HasForeignKey("DiscountId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany()
                        .HasForeignKey("OrderDetailFeedbackId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderDetailFeedback");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedbackMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", "OrderDetailFeedback")
                        .WithMany("OrderDetailFeedbackMediaList")
                        .HasForeignKey("OrderDetailFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetailFeedback");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductList")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany("ProductList")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductDiscount", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductDiscountList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductFeedback", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductFeedbackList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductMedia", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Product", "Product")
                        .WithMany("ProductImageList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Subscription");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserAddressList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.UserPayment", b =>
                {
                    b.HasOne("Antree_Ecommerce_BE.Domain.Entities.User", "User")
                        .WithMany("UserPaymentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Discount", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetailList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.OrderDetailFeedback", b =>
                {
                    b.Navigation("OrderDetailFeedbackMediaList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetailList");

                    b.Navigation("ProductDiscountList");

                    b.Navigation("ProductFeedbackList");

                    b.Navigation("ProductImageList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAddressList");

                    b.Navigation("UserPaymentList");
                });

            modelBuilder.Entity("Antree_Ecommerce_BE.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
